services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
      target: dev
    working_dir: /app/apps/frontend
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/packages/shared/node_modules
      - /app/apps/frontend/.next
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - WATCHPACK_POLLING=1
