services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
